### ISSUE TITLE
Personal error or pack error?

### ISSUE THREAD

**Issue by imladris3000** [John-Smith-Modded/JSTR-Modded-1.12.x#1]
Hello there. I went and downloaded the zip to try this out and see what it looked like on my minecraft 1.12.2 world (because i have really liked the past john smith technician packs) and it is not working out all that well. I think it may be a 'me' mistake but i just wanted to be sure. I placed the zip in my resource pack folder where my other resource packs have gone before it.... and it wont register?! when i load up minecraft and look at the list of texture packs available, your beautiful texture pack does not show up, yet if i hit the button that takes me to the texture pack folder i can see it sitting in there. (i am using forge1.12.2-14.23.1.2555)

**Comment by Oddface** [comment]
Our modded repositories are not structured like resource packs. To make a functional resource pack you need to extract the contents of each of the mod folders into a regular resource pack (like the "vanilla" repositories we have, which do work like resource packs). We should have an official release pretty soon.

**Comment by Trixz2018** [comment]
yeah i tried that and nothing worked, tried to load it and minecraft just kicked it back out and all textures were broke and then minecraft just kept crashing. 
PS: either the curse page link is broken or it doesn't exist. love the work and wish i could get my hands on a working modded version for 1.12.2

**Comment by ScottKillen** [comment]
Curse page link works fine. Here is the link: [https://www.curseforge.com/minecraft/texture-packs/john-smith-legacy-modded](https://www.curseforge.com/minecraft/texture-packs/john-smith-legacy-modded)

309,150 downloads

**Comment by Trixz2018** [comment]
there is no 1.12.2 update, the latest is 1.10.2

**Comment by ScottKillen** [comment]
Ah. Now I understand.

**Comment by Trixz2018** [comment]
yup :(

**Comment by damonmensch** [comment]
I will manually generate a release for you and post it. It'll be up later
tonight.

**Comment by Trixz2018** [comment]
cool thanks :) ill try and do some art in return for mods you don't have textures for yet

**Comment by damonmensch** [comment]
Please see the attached release. https://github.com/John-Smith-Modded/JSTR-Modded-1.12.x/releases/latest

**Comment by Trixz2018** [comment]
thanks for the pack unfortunately it kept causing me to crash so i had to remove it, it seems to be something with chisel so i am gonna dissect it and find out what is causing it to crash

**Comment by Trixz2018** [comment]
ok its not chisel its something else and i do not know, so im gonna try and figure something out

**Comment by Trixz2018** [comment]
so i took the 1.10.2 version and 1.7.10 version and combined bits and pieces of each along with another texture pack and got a frankenstein texture pack to work

**Comment by Trixz2018** [comment]
ok so the issue with the latest pack is caused by thermalfoundation any ore_fluid mcmeta file because if they are empty they will crash the client cause fml doesn't like it being empty. Once i deleted the three, i was able to use it.

**Comment by ScottKillen** [comment]
Probably should report this over at https://github.com/MinecraftForge/MinecraftForge because vanilla Minecraft can deal with empty mcmeta files.

**Comment by Oddface** [comment]
I was putting them in out of habit, but I guess you no longer need to have mcmeta files when overwriting animated textures with non-animated ones?
