### ISSUE TITLE
Resource Pack not working correctly, All The Mods v.3

### ISSUE THREAD

**Issue by Adviser69** [John-Smith-Modded/JSTR-Modded-1.12.x#11]
I just started playing on the official All The Mods server, and tried to implement the latest release of this resource pack. When I logged into the server, this is what I got:
![2018-04-01_09 00 05](https://user-images.githubusercontent.com/8868488/38175189-5a7522ca-358d-11e8-9420-19def25abd48.png)
I got the same result with single player as well. I even tried the overwrite patch to no avail. I'm not getting any crashes, just this strange texture setup (Or lack thereof). For reference, the trees are birch and dark oak, there is water to the left, ferns and trees to the right, and I'm holding a book.

**Comment by JeffKazuk** [comment]
Problem seems to lie in tinker's construct similar to a few of the other issues.

Remove the tconstruct folder and the issue should be resolved

**Comment by lesdmark** [comment]
This was Mojang's idea of an April Fools prank. Closing as there is no issue.
