### ISSUE TITLE
JSTR unable to resolve due to upward reference, disabling pack and reverting to vanilla

### ISSUE THREAD

**Issue by MutantMannequin** [John-Smith-Modded/JSTR-Modded-1.12.x#13]
EDIT: I tested the mod assets in blocks to narrow it down, and I've isolated the problem to the assets from JSTR-Modded-1.12.x-master/Tinkers_Construct/assets/tconstruct. I've added all the other assets to the resource pack without issue, now, and they're running fine. Adding tconstruct assets causes the issue.

I'm running FTB Revelation with Optifine_1.12.2_HD_U_D3. John Smith Legacy works fine, but when I add the assets from ~~the JSTR repo~~ **tconstruct** , either as a separate pack or inside John Smith Legacy, the client automatically disables the pack to revert to default. (It also replaces the main menu with the undefined texture until I restart the client, but that doesn't really matter.)

Here's the fml log from the last time I tried.

[latest.log](https://github.com/John-Smith-Modded/JSTR-Modded-1.12.x/files/2052479/latest.log)

**Comment by lesdmark** [comment]
I realize this response is late but I will check it out as soon as a I get a moment.
