### ISSUE TITLE
[Suggestion] Updated GUIs for Thermal Expansion machines

### ISSUE THREAD

**Issue by darthvader45** [John-Smith-Modded/JSTR-Modded-1.12.x#14]
Seeing as TE changed a bit in the 1.12.x age, might want to update the GUIs for the machines.  Some buttons are hidden or weirdly placed.

**Comment by lesdmark** [comment]
I will take a look at this as soon as I get a moment. I had stepped away from Minecraft for a bit, but am starting to get the pull again.

**Comment by darthvader45** [comment]
Alrighty, cannot wait to see what could come out of this.  Do what ya gotta do, I'll be playing Minecraft like usual.

**Comment by lesdmark** [comment]
I have not forgotten about this, just been a bit busy. Sorry for the delay.

**Comment by darthvader45** [comment]
It's alright. Take as long as ya need.

**Comment by lesdmark** [comment]
So I have started to correct the gui issues got all the incorrect ones in the gui\device folder fixed. Need to add three more and that will be done. Moving on to the rest now.

**Comment by darthvader45** [comment]
Thanks bro, you made my day.  As long as the machines' GUIs are fixed, I'm happy.

**Comment by lesdmark** [comment]
Machine GUI's are now fixed that already had textures. As soon as I get the chance I will try to create the missing machines but no more weird GUI's. Let me know if there are still any issues with what I fixed.

**Comment by darthvader45** [comment]
Alrighty, will check right away.

**Comment by darthvader45** [comment]
Just curious, will I have to pull the GUI textures from the repo, or is there a release out now?

**Comment by lesdmark** [comment]
Sorry for the very late response. You will need to pull them. As far as I know there is not a newer release. I also have started updating some of the other mods files to be compatible so make sure to check those out as well.

**Comment by darthvader45** [comment]
Awesome, I pulled em and they indeed look great.  Thanks so much for the
effort man, I am eternally grateful.

**Comment by lesdmark** [comment]
I have just started working on the GUI's for IC2 and just made sure the existing forestry ones should be ok. Let me know if you find anything there if you use those mods.

**Comment by darthvader45** [comment]
Will do, keep up the good work.

**Comment by darthvader45** [comment]
Will do, keep up the good work.
