### ISSUE TITLE
Simple Corn support

### ISSUE THREAD

**Issue by Eniam** [John-Smith-Modded/JSTR-Modded-1.12.x#15]
Hello there,

Haven't uploaded anything before and not sure how you all go about additions but I've made a crude 32x texture for Simple Corn that I'd like to submit. The JSTR team can do with it what they wish, 100%- I am retaining no rights implied or otherwise. Hope that's good enough for a waiver and I hope you're able to use it somehow. If there's a process for submitting them, as well as key points you try to achieve within the textures themselves I'd like to understand so I can update some others I'm missing. Apologies if this is in the wrong place.

[simplecorn.zip](https://github.com/John-Smith-Modded/JSTR-Modded-1.12.x/files/2477186/simplecorn.zip)

Thanks, 
Eniam

**Comment by lesdmark** [comment]
I took a look at what you had and I would recommend looking at the crop growing textures in Pam's for inspiration to get closer to the look we need. It is perfectly acceptable to take stuff from existing textures within the pack and modify them to suit your needs as well. Good luck!
