### ISSUE TITLE
Domain no longer owned by John Smith?

### ISSUE THREAD

**Issue by JLLeitschuh** [John-Smith-Modded/JSTR-Modded-1.12.x#16]
This link in the README now points to a domain squatter.

http://js-legacy.net/

**Comment by lesdmark** [comment]
I have changed the readme file to reflect this thanks for the heads up!

**Comment by lesdmark** [comment]
I am reopening this issue as I cannot change the link on the repository itself. Someone with more power than me will need to do that.

**Comment by artdude543** [comment]
Custom DNS removed. DNS is being purged by GitHub.

**Comment by lesdmark** [comment]
Sweet. Thanks a bunch.
