### ISSUE TITLE
Push the 1.12 version of modded to curse

### ISSUE THREAD

**Issue by lesdmark** [John-Smith-Modded/JSTR-Modded-1.12.x#18]
Could we get the current version of the 1.12 pack pushed to Curse/Curseforge. There is currently no 1.12 version listed at all on either. I am still adding content on a regular basis again to the 1.12 version to try to get it as good as some of the more popular packs as far as coverage.

**Comment by damonmensch** [comment]
I wish they would grant more of us the perms t ok do the pushes. The automated script hasn't worked for months, maybe even over a year

**Comment by lesdmark** [comment]
It does make it hard to keep the pack fresh.

**Comment by artdude543** [comment]
I can explain what's been going on in regards to the script en all. But it's not for this GitHub. So if you have Discords I can invite you to the Fanver one to explain the whole dealeo.

**Comment by artdude543** [comment]
I also have built an updated ZIP using the packager which I can upload to Curse if you wish.

**Comment by lesdmark** [comment]
my discord name is the same as here

**Comment by artdude543** [comment]
What're your 4 digits?

**Comment by lesdmark** [comment]
9691

**Comment by lesdmark** [comment]
Joined successfully

**Comment by damonmensch** [comment]
Mine also is the same. 4 digits are 3310

**Comment by lesdmark** [comment]
Thanks for the update, and updating it on curse. Closing issue now.
