### ISSUE TITLE
Ender io capacitor bank "energy bar" not showing

### ISSUE THREAD

**Issue by skalapunk** [John-Smith-Modded/JSTR-Modded-1.12.x#25]
normally you can wrench the side of a capacitor bank and toggle between different states, such as in/out, or a bar graphic that shows, at a glance, how much energy is in the bank. With JSTR, The empty space for the bar is there, but there's no visible bar

**Comment by lesdmark** [comment]
Hmm, I will take a look at it as soon as I get a chance. Those textures might have just been straight ported with no adjustments from 1.7 to 1.12

**Comment by lesdmark** [comment]
Energy Bar overlay is now fixed. You can either go ahead and download the corrected texture here or wait until a new release is pushed which will be soon!
