### ISSUE TITLE
Game crashes on launch with texture pack

### ISSUE THREAD

**Issue by Naddox** [John-Smith-Modded/JSTR-Modded-1.12.x#3]
Just downloaded the pack and activated it on my minecraft, game crashed instantly after setting it to active. Tried relaunching game and just continues to crash. Tried removing the smooth pack and just have the base pack and still crashes on launch.

gist link for fml-client-latest.log
https://gist.github.com/Naddox/9dbe6916692af7a4947fb0188541cce3

**Comment by ScottKillen** [comment]
Sorry...but the log is not complete. It does not show a crash or any kind of program termination at the end.

This is probably related to #2 . Please post logs there.
