### ISSUE TITLE
Pam's Harvestcraft Textures Not Applying

### ISSUE THREAD

**Issue by AvidChemist** [John-Smith-Modded/JSTR-Modded-1.12.x#32]
![githelp](https://user-images.githubusercontent.com/30247137/56228656-32eed180-6046-11e9-8ed2-d22b10e9c711.png)

Here is a screenshot of what I'm experiencing. I took a peek through both the Buildcraft and Pam's Harvestcraft repositories and noticed that a few things were not showing up with the new textures in my game. Most things seem to work, but I found a texture for the hopper/chute which is still appearing as default. Most Buildcraft things seem to function appropriately, and I noticed there are no particles when breaking transport pipes but as there are some blocks specifically labeled "Work in Progress" I imagine the particles are also a non-issue.

![githippity](https://user-images.githubusercontent.com/30247137/56228515-fcb15200-6045-11e9-9aff-fda3289f12eb.png)

The more tedious part to me is how some of the Harvestcraft textures are applying properly, the apple and wheat for example. But the majority of items do not. Through the repository I see that there aren't any blocks with new textures so I'm not really worried about that. 

I've tried the curse pack, manually updating each piece of the repository into said curse pack, unzipping the resource pack and using the twitch launcher to apply the resource pack. (I'm using regular Java Edition, I think. ) I tried a resource pack that was uploaded somewhere in a previously resolved issue thread for someone who was having a similar problem with different mods. I've updated and downgraded forge, updated Pam's Harvestcraft (I first downloaded the mod sometime in March), and I've had my friend try to replicate the error on their computer. I'm kind of at a loss lol. I was hesitant to post and now here's a whole wall. Thanks in advance and I love the work you guys are doing!

**Comment by lesdmark** [comment]
I will take a look at them and see what the issue might be. Haven't been playing for a few days and had not loaded the pack since those things were added.

**Comment by lesdmark** [comment]
Pam's textures now work. The I in the word item of each filename was uppercase. The newer versions of the pack are all lowercase, and apparently it is case sensitive.

**Comment by lesdmark** [comment]
Alright existing texture in buildcraft is now corrected to match the 1.12 version. Any more issues are related to the texture just not existing yet for the pack. those todo's are in buildcraft itself and not anything in the pack. Make sure to delete out all your pams textures before readding them as windows likes to pretend like case doesn't matter and will cause issues if you don't completely get rid of the old textures. Have a good one!
