### ISSUE TITLE
Railcraft Support

### ISSUE THREAD

**Issue by DaddyCecil** [John-Smith-Modded/JSTR-Modded-1.12.x#34]
https://minecraft.curseforge.com/projects/railcraft

Got an update pushed for 1.12 about two months ago, would love to see textures for this mod!

**Comment by lesdmark** [comment]
I will take a look and see how many of the old textures can be straight ported and see about another release.

**Comment by lesdmark** [comment]
All the textures that could be ported have been. Will work on the missing textures when I get a chance.
