### ISSUE TITLE
where to add this zip?

### ISSUE THREAD

**Issue by Nemeruis** [John-Smith-Modded/JSTR-Modded-1.12.x#37]
do I have to put all in mods or is there an other way to do it

**Comment by damonmensch** [comment]
You need to build a zip with the proper meta data file in it and then combine the contents of every base folder, excluding the mod.json, into the zip.

Example:

The assets folders from appleskin and applied energistics 2.

You would do this for every mod you want in the zip.

**Comment by Nemeruis** [comment]
thank you

**Comment by lesdmark** [comment]
The zip files I add under each [release](https://github.com/John-Smith-Modded/JSTR-Modded-1.12.x/releases) are the complete pack up to that point. They  just need to be dropped into your resourcepack folder to work. No doing all that work yourself necessary. (it's the JSTR.1.12.x.zip file)
