### ISSUE TITLE
Biomes O' Plenty Redwood Leaves Missing Color

### ISSUE THREAD

**Issue by Exsolutus** [John-Smith-Modded/JSTR-Modded-1.12.x#38]
Attached is a screenshot of the Redwood Leaves with the texture pack enabled. All other leaves textures appear to be working correctly.

![2019-06-15_16 16 01](https://user-images.githubusercontent.com/23705866/59555961-16f5a680-8f89-11e9-848e-8321d4407dc2.png)

**Comment by lesdmark** [comment]
I will take a look at it when I get a chance.

**Comment by lesdmark** [comment]
The [1.2.5a](https://github.com/John-Smith-Modded/JSTR-Modded-1.12.x/releases/tag/MC1.12.x-v1.2.5a) release solves this issue. Enjoy!
