### ISSUE TITLE
Crash at loading with Tinker's Construct assets

### ISSUE THREAD

**Issue by Filvandrel** [John-Smith-Modded/JSTR-Modded-1.12.x#4]
Hello!
I'm having a crash at loading when I'm using Extrautils 2, Tinker's Construct and Tinker's assets in this resourcepack. Without tinker's assets everything loads fine. Without Extrautils textures works fine. But If I'm using Tinker's assets and Extrautils at the same time, I get the crash.

Here's the crash log:
https://pastebin.com/DXt27L9b

**Comment by ScottKillen** [comment]
This has been reported to the Tinker's Construct team. Please see #2
