### ISSUE TITLE
Possible incompatibility with Serene Seasons

### ISSUE THREAD

**Issue by Shandoo94** [John-Smith-Modded/JSTR-Modded-1.12.x#40]
Version MC1.12.x-v1.2.0a
Forge: 14.23.5.2838

The mod Serene Seasons changes the color of grass nd leaves as the season changes. some grass block and all leaves don't change color with the season (see screenshots).

![2019-07-19_08 31 56](https://user-images.githubusercontent.com/21018028/61540268-97527000-aa3d-11e9-98e0-b56c763b9165.png)
![2019-07-19_08 39 37](https://user-images.githubusercontent.com/21018028/61540269-97527000-aa3d-11e9-81dc-1f1183251007.png)

**Comment by lesdmark** [comment]
The problem would have to be on the mods end as there is nothing different this pack does compared to the way vanilla does the same thing. I would suggest checking another pack for test purposes to see if the issue persists. Also make sure to report the issue to the mod author as well.
