### ISSUE TITLE
Redstone Torch texture issue

### ISSUE THREAD

**Issue by Shandoo94** [John-Smith-Modded/JSTR-Modded-1.12.x#42]
Version MC1.12.x-v1.2.0a
Forge: 14.23.5.2838

![2019-07-19_19 17 34](https://user-images.githubusercontent.com/21018028/61589729-c50af680-abae-11e9-96d1-803210e0b03d.png)

The textures are normal in the lates version aviable on curse from Apr 14, 2019.

![2019-07-20_18 01 29](https://user-images.githubusercontent.com/21018028/61589733-d0f6b880-abae-11e9-9ffa-a064eadb0a69.png)

The lates GitHub release is missing the files "redstone_torch.json" and "redstone_torch_wall.json" in assets\minecraft\models\block\

Adding both files to the archive partially fixed the issue

![2019-07-20_18 40 52](https://user-images.githubusercontent.com/21018028/61589735-e5d34c00-abae-11e9-8007-c69e1c99f226.png)

**Comment by lesdmark** [comment]
This issue was moved to the 1.12 vanilla texture repository. Please do not open duplicate issues without checking the status of a previous issue.
