### ISSUE TITLE
Texture issue creosote oil

### ISSUE THREAD

**Issue by Shandoo94** [John-Smith-Modded/JSTR-Modded-1.12.x#43]
Version MC1.12.x-v1.2.0a
Forge: 14.23.5.2838

![2019-07-21_12 01 39](https://user-images.githubusercontent.com/21018028/61589782-68f4a200-abaf-11e9-880e-2affc2fcae84.png)

**Comment by lesdmark** [comment]
The textures in the repo were corrupted duplicates of the original so they were deleted. The issue should now be resolved.
