### ISSUE TITLE
Thaumcraft Arcane Lamp texture is pink

### ISSUE THREAD

**Issue by ZeroKaion** [John-Smith-Modded/JSTR-Modded-1.12.x#44]
I'm playing the Enigmatica Expert 2 modpack with my friend and when im using JSTR my arcane lamp from Thaumcraft goes pink quickly after placing it. Unlit texture is fine. My friend do not use JSTR and can see the lamp just fine. 

Thaumcraft-1.12.2-6.1.BETA26

**Comment by lesdmark** [comment]
All the lamp texture were missing their files that animate them. This has now been corrected. I will be uploading a corrected version of the pack to GitHub in a bit. I will post a link here when I do so you don't have to hunt for it.

**Comment by lesdmark** [comment]
[Here](https://github.com/John-Smith-Modded/JSTR-Modded-1.12.x/releases/download/MC1.12.x-v1.2.5b/JSTR.1.12.x.zip) is the link to the corrected release. let me know if either thing is still a problem
