### ISSUE TITLE
Thaumcraft Focal Manipulator UI outdated.

### ISSUE THREAD

**Issue by ZeroKaion** [John-Smith-Modded/JSTR-Modded-1.12.x#45]
Thaumcraft Focal Manipulator UI is outdated and glitchy.

Thaumcraft-1.12.2-6.1.BETA26

**Comment by lesdmark** [comment]
I have removed the GUI texture completely as it is just causing an issue due to being completely wrong. I also corrected another texture that was no longer correct. If you know how you can delete the texture yourself, or wait for the next release.
