### ISSUE TITLE
Immersive Engineering wallmounts

### ISSUE THREAD

**Issue by sprocketx** [John-Smith-Modded/JSTR-Modded-1.12.x#46]
The wallmount textures for immersive engineering are have a spelling error in the file names, however when corrected they don't wrap around the model correctly leaving transparent spaces.

**Comment by lesdmark** [comment]
As of [this fix](https://github.com/John-Smith-Modded/JSTR-Modded-1.12.x/commit/c78549388cd855636ba732e9b828f13268672484) the issue has been resolved. If you have any further issues. Let us know.
