### ISSUE TITLE
Biomes O'Plenty Use

### ISSUE THREAD

**Issue by RoseandWood** [John-Smith-Modded/JSTR-Modded-1.12.x#48]
This is likely a really stupid question and I apologize for not knowing the answer. I'm not sure where else to ask. I have a modded 1.14.4 server that is using Biomes O'Plenty. I have John Smith Legacy as a Resource Pack. I added the BOP textures from the JSTR Modded pack to the John Smith Legacy pack so those textures would be in-game as well. However, I've loaded up the game and the BOP resources are still original vanilla. Can I just get an appropriate guide on proper installation of the John Smith BOP textures? I want to correct that as John Smith is a beautiful pack and I'd love to see its impact on BOP.

**Comment by lesdmark** [comment]
I would assume there is a difference to what BOP did with it's textures between 1.12 and 1.14 (could just be name changes) that is usually what makes textures fail to work at all. If you are not familiar with texture pack creation, there are most likely YouTube videos that teach how to make texture packs. If you don't want to make that leap then the only option would be to wait until there is a 1.14 version of this pack.
