### ISSUE TITLE
Tinker's Construct & Path

### ISSUE THREAD

**Issue by RechargeableAA** [John-Smith-Modded/JSTR-Modded-1.12.x#5]
Tinker's Construct has corrupted png's. returns error "Divided by zero". 
Path is currently set up as mod>assets>mod>textures>etc. should be mod>textures>etc

**Comment by Oddface** [comment]
The GitHub folder structure is not intended to be used as is, but to be assembled by a script, as explained here: https://github.com/John-Smith-Modded/JSTR-Modded-1.7.x/issues/182

As the script is down at the moment, we'll occasionally post updates in the Releases section: https://github.com/John-Smith-Modded/JSTR-Modded-1.12.x/releases
