### ISSUE TITLE
Old wool textures for Tudor style buildings

### ISSUE THREAD

**Issue by mccoole** [John-Smith-Modded/JSTR-Modded-1.12.x#53]
Installed the modded version from Curse but the wool blocks are plain now.  Still showing as 32 bit but they no longer have the framing.  Is there still a way to use these textures in the modded version or do I need to do something like overlaying the John Smith Legacy vanilla?  Thanks!

**Comment by ScottKillen** [comment]
@mccoole [JSTR Vanilla](https://github.com/John-Smith-Modded/JSTR-Vanilla-1.12.x) overrides the wool blocks from [JohnSmith Legacy](https://www.johnsmithlegacy.co.uk/). This pack uses JSTR Vanilla as a base.

You can replace the wool in this pack with the wool in JohnSmith legacy to get those specific blocks back, or, you can create a tiny resourcepack containing only those wool blocks in the correct path, with a `pack.mcmeta` file at its root. Put this new resource pack above JSTR in the load order and it will overwrite the new wool with the old textures.
