### ISSUE TITLE
Spartan Weaponry

### ISSUE THREAD

**Issue by LeYakuzaFou** [John-Smith-Modded/JSTR-Modded-1.12.x#59]
Hello,
i wanted to know if it was possible to do some custom texture for Spartan weaponry, Spartan Shield and Spartan and fire for 1.12.2.
Because i really wanted to see texture of this pack go with spartan mods

**Comment by lesdmark** [comment]
You are more than welcome to submit a pull request with textures for the mod you have mentioned and I can take a look to see if I can approve it if it meets the criteria.
