### ISSUE TITLE
New crash with 1.1.5 version, ImmersiveEngineering Stitching texture

### ISSUE THREAD

**Issue by Naddox** [John-Smith-Modded/JSTR-Modded-1.12.x#6]
[Here is the full crash log](https://gist.githubusercontent.com/Naddox/11bb21e329ca4b69750a65595d9eb0ef/raw/3edbb262682223067e41a38a248dc8e5e24144b4/fml-client-latest.log%252002-04-18)

[And here is just the tail end with the actual crash info](https://gist.github.com/Naddox/cad71918c5ae4a380b7e6cd9b4fdf20f)

Crash occurred while applying the JSTR texture pack at the main menu. Playing a custom pack

**Comment by artdude543** [comment]
Okay, this is odd as it's related to another crash. Something is looking for Ardite which literally does not exist as own textures. Do you have any ideas on this @bonii-xx?

**Comment by bonii-xx** [comment]
Ardite has a texture which is also used to generate the tool part textures: https://github.com/SlimeKnights/TinkersConstruct/blob/1.12/resources/assets/tconstruct/textures/items/materials/ardite_rust.png

What I don't understand is the crash though. Widgth/Height 1x1? What texture size is the resourcepack using? I wonder if it's got something to do with different sizes (which should be handled gracefully everywhere, but you never know)

**Comment by lesdmark** [comment]
Closing this as it appears to have been resolved.
