### ISSUE TITLE
Update Witchery textures (1.7.10)

### ISSUE THREAD

**Issue by juwood0309** [John-Smith-Modded/JSTR-Modded-1.12.x#60]
The most recent version of the 1.7.10 pack includes partial Witchery textures along with a few other non updated mods.

**Comment by lesdmark** [comment]
This is a statement, not a bug report or request. Also 1.7.10 is 7 years old at this point and this is the 1.12 branch. If you want something added to 1.7.10 feel free to create the textures and submit them on the 1.7.10 branch as a pull request.
