### ISSUE TITLE
Instantly crashes to desktop, FTB Revelations on Minecraft 1.12.2

### ISSUE THREAD

**Issue by Le-PiedPiper** [John-Smith-Modded/JSTR-Modded-1.12.x#9]
Hi guys, its been a while since I've played minecraft or tried to put on a texture pack but I think I've been doing this correctly. 
I've downloaded the most up to date commit and then downloaded the master file and replaced all the commits assets with the master files updated asset files.
However, whenever i go into the menu and select the resource pack it loads then crashes instantly. I have no crash reports or anything it just dies instantly. Any help properly installing the pack or any help with the issue would be greatly appreciated.

**Comment by edwardszGhost** [comment]
I have the exact same issue. I've only used the latest release and it crashes at startup. I did get a crash report so here it is.
[crash-2018-03-14_20.55.32-client.txt](https://github.com/John-Smith-Modded/JSTR-Modded-1.12.x/files/1813129/crash-2018-03-14_20.55.32-client.txt)

**Comment by W-Schnee** [comment]
I get pretty much the same error log with this pack. 
I can confirm that other 32x and even 64x packs work just fine (tested [Sphax 32x and 64x](http://bdcraft.net/community/pbdc-patches-rel-packs/feed-the-beast-revelation-t6358.html))

**Comment by joeshimmo** [comment]
If any of you are still having this problem I managed to fix it by removing the tconstruct folder (I downloaded the latest version at https://github.com/John-Smith-Modded/JSTR-Modded-1.12.x/releases).

**Comment by lesdmark** [comment]
I edited the Tcon folder so hopefully it will no longer happen.
